# Generated by Django 5.1 on 2024-08-30 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UniversityCampus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campus_name', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=2)),
                ('campus_id', models.IntegerField()),
            ],
            options={
                'verbose_name': 'University Campus',
            },
        ),
    ]
